### ISSUE TITLE
Regarding the Translation of JSON Files

### ISSUE THREAD

**Issue by NightbirdChild** [mtzimas92/MHServerEmu-CatalogManager#11]
<img width="645" height="444" alt="Image" src="https://github.com/user-attachments/assets/477c5495-1f50-41e0-a687-1ab68eae591b" />
<img width="502" height="386" alt="Image" src="https://github.com/user-attachments/assets/bdf2a00a-6d78-4189-8c8b-49feef83e1ba" />
<img width="732" height="891" alt="Image" src="https://github.com/user-attachments/assets/72bb4fe9-add5-4e10-a5cd-3e1a97ddc18a" />
<img width="1182" height="891" alt="Image" src="https://github.com/user-attachments/assets/0875c4c7-0813-44a9-ad60-683a65c03c16" />
<img width="732" height="891" alt="Image" src="https://github.com/user-attachments/assets/288f2602-c10f-4dcb-a35b-73d67319ce4b" />
<img width="2070" height="80" alt="Image" src="https://github.com/user-attachments/assets/b42a7e33-f9f1-4878-b72f-648924a94089" />

The above are the untranslated texts currently visible. Some texts still do not display the translated content even after I modify the JSON files.

**Comment by NightbirdChild** [comment]
Yes, if localized Chinese text is directly input into the game, the game will definitely fail to recognize it, leading to in-game errors. Therefore, we only need to localize the displayed text—the original English code should still be the one written into the game.
This sounds simple in theory, but implementing it may be quite tricky. I can only ask you to look into it and research possible solutions. If it can be realized, that would be ideal; if not, it will be a pity, but there’s nothing we can do about it.

**Comment by mtzimas92** [comment]
Okay. I have fixed most of these. There is no way for me to change the Item name and category from the catalog files however. 

I will update everything later today.

**Comment by mtzimas92** [comment]
Released the new version for you.

**Comment by NightbirdChild** [comment]
Below are the issues currently existing.

<img width="948" height="333" alt="Image" src="https://github.com/user-attachments/assets/40241fd9-b814-4647-a152-0289f64732da" />

Is it normal that there is no type information when opening the CatalogEmpty.json file?

I modified the display_names.json file under the data folder, but the titles in the interface still show the original ones.

**Comment by mtzimas92** [comment]
Ah also, you may want to update the display names file in the main folder to show your items in your language. 

But you will not see any loaded items (any item in Catalog files) to have a non-English locale.
